global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]
      - targets: ["otel-collector:8888"]
  - job_name: otel
    honor_labels: true
    static_configs:
      - targets:
          - "otelcol:9464"
