version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
