version: "3.9"
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: otel-collector
    command:
      [
        "--config=/etc/otel-collector.yaml",
        "--feature-gates=pkg.translator.prometheus.NormalizeName",
      ]
    volumes:
      - ./docker/otel-collector/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "8888:8888" # Prometheus receiver
      - "8889:8889" # Prometheus receiver
    depends_on:
      tempo:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:13133/ready || exit 1
    logging: *logging
    networks:
      - bridge-network

  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/status || exit 1
    restart: unless-stopped
    logging: *logging
    networks:
      - bridge-network

  grafana:
    image: grafana/grafana:10.3.4
    container_name: grafana
    extra_hosts: ["host.docker.internal:host-gateway"]
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    restart: unless-stopped
    logging: *logging
    networks:
      - bridge-network

  loki:
    image: grafana/loki:2.9.5
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker/loki/loki.yaml:/etc/loki/local-config.yaml:ro
    logging: *logging
    networks:
      - bridge-network

  tempo:
    image: grafana/tempo:2.4.0
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml:ro
      - ./vol/tempo:/tmp/tempo
    ports:
      - "3200:3200"
      - "4417:4317"
      - "4418:4318"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:3200/status || exit 1
    logging: *logging
    networks:
      - bridge-network

networks:
  bridge-network:
    name: bridge-network
    driver: bridge
