version: "3.9"

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command:
      [
        "--config=/etc/otel-collector.yaml",
        "--feature-gates=pkg.translator.prometheus.NormalizeName",
      ]
    volumes:
      - ./.config/otel/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    depends_on:
      - prometheus
      - jaeger
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./.config/prometheus/prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --storage.tsdb.retention.time=1h
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
    ports:
      - "9090:9090"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/status || exit 1
    restart: unless-stopped
    networks:
      - bridge-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    extra_hosts: ["host.docker.internal:host-gateway"]
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - prometheus
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    restart: unless-stopped
    networks:
      - bridge-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - bridge-network

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: on-failure
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:5341 || exit 1
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
