version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=drugstore
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - bridge-network

  cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - ./cache-data:/data
    networks:
      - bridge-network

volumes:
  db-data:
  cache-data:

networks:
  bridge-network:
    driver: bridge
